[project]
name = "read-daq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.5",
    "nidaqmx>=1.2.0",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "pyqtgraph>=0.13.7",
    "pyside6==6.9.0",
]
